### ISSUE TITLE
write EPIPE error in aws lambda

### ISSUE THREAD

**Issue by Mrutyunjay1992** [navjotdhanawat/dynamic-html-pdf#19]
ERROR	{ Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at PDF.PdfExec [as exec] (/var/task/node_modules/html-pdf/lib/pdf.js:141:15)
    at PDF.PdfToBuffer [as toBuffer] (/var/task/node_modules/html-pdf/lib/pdf.js:44:8)
    at Promise (/var/task/node_modules/dynamic-html-pdf/index.js:40:24)
    at new Promise (<anonymous>)
    at Object.module.exports.create (/var/task/node_modules/dynamic-html-pdf/index.js:25:12)
    at Promise (/var/task/routes/ar_invoice.js:795:17)
    at new Promise (<anonymous>)
    at exportHtmlToPdf (/var/task/routes/ar_invoice.js:763:16)
    at ar_checklist_details.findAll.then (/var/task/routes/ar_invoice.js:379:80)
    at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/var/task/node_modules/bluebird/js/release/async.js:138:12) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }

**Comment by JanScheeleDev** [comment]
We had this problem with an ec2 instance. We did not have the correct platform version for phantomJS. This article helped us: https://sebastien-carceles.medium.com/install-phantomjs-on-aws-elastic-beanstalk-with-ebextensions-d621decdc75
